- name: start_docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "ubuntu"
    group: "docker"
    append: yes