- name: Install dependency package
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: present
  become: yes
  tags: docker

- name: Add Apt key
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  become: yes
  tags: docker

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  become: yes
  tags: docker

- name: Install Docker
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  notify: start_docker
  tags: docker
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "ubuntu"
    group: "ubuntu"
    groups:
      - docker
    append: yes

- name: Install pip3
  ansible.builtin.apt:
    name: 
      - python3-pip
    state: present
    update_cache: yes
  become: yes
  
- name: Install Python docker library
  ansible.builtin.pip:
    state: present
    name: docker